name       : cln
version    : 1.3.6
release    : 2
source     :
    - https://www.ginac.de/CLN/cln-1.3.6.tar.bz2 : f492530e8879bda529009b6033e1923c8f4aae843149fc28c667c20b094d984a
homepage   : https://www.ginac.de/CLN/
license    : GPL-2.0-or-later
component  : programming
summary    : CLN - Class Library for Numbers
description: |
    CLN is a library for efficient computations with all kinds of numbers in arbitrary precision.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
