name       : cln
version    : 1.3.4
release    : 1
source     :
    - http://www.ginac.de/CLN/cln-1.3.4.tar.bz2 : 2d99d7c433fb60db1e28299298a98354339bdc120d31bb9a862cafc5210ab748
license    : GPL-2.0
component  : programming
summary    : CLN is a library for efficient computations with all kinds of numbers in arbitrary precision.
description: |
    CLN is a library for efficient computations with all kinds of numbers in arbitrary precision.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
